### ISSUE TITLE
✨와인 데이터 크롤링

### ISSUE THREAD

**Issue by mobzzzzz** [spartaKotlinTeamSober/wachu_server#11]
# 기능 설명
DB에 필요한 와인 데이터를 크롤링합니다. (ex: wine folly)

# To-do
- [x] 와인 데이터 크롤링 성공 (DB Column에 필요한 내용들) ※ 크롤러 IP 밴 주의!
- [x] 크롤링 된 데이터를 외부 파일 (txt등) 으로 저장
- [x] 크롤링 된 데이터를 DB에 저장

# ETC
To-do가 커진다면 이슈 분리해주세요!

H2 DB를 사용하는 동안에 계속 와인 데이터를 날릴 수는 없으니
H2 DB를 각자 컴퓨터에서 Embedded 모드 / Server 모드로 사용하다가 RDS로 넘어가는게 좋을 수도 있어보입니다.
(H2 DB 설치 메뉴얼도 알려주세요!)

**Comment by npureaun** [comment]
webCrawler / fileReader 리포지토리 생성. 노션 5분기록보드에 설명서 있습니다.
