### ISSUE TITLE
✨개인정보 처리

### ISSUE THREAD

**Issue by mobzzzzz** [spartaKotlinTeamSober/wachu_server#113]
# 기능 설명

작업할 기능에 대한 설명 작성

# To-do

- [x] Soft delete + status 추가
- [x] Created at 추가
- [x] 개인정보 약관 대충 작성
- [x] 회원 탈퇴 추가

# ETC
