### ISSUE TITLE
✨이미지가 필요한 API 이미지 설정

### ISSUE THREAD

**Issue by mobzzzzz** [spartaKotlinTeamSober/wachu_server#14]
# 기능 설명
이미지를 받는 API들에 이미지를 추가합니다.

# To-do
- [x] 멤버 프로필 사진 추가
- [x] 페어링 사진 추가
- [x] 리뷰 **멀티미디어** 추가 (여러 장의 사진 가능)

# ETC
멀티미디어는 작업 분량이 커지면 이슈 분리하시면 됩니다

**Comment by npureaun** [comment]
api뚫었다!
