### ISSUE TITLE
✨와인페어링 도메인 기본적인 구조만 작성

### ISSUE THREAD

**Issue by mobzzzzz** [spartaKotlinTeamSober/wachu_server#2]
# 기능 설명
와인페어링 도메인의 기본적인 구조를 **로직을 제외하고** 기본적인 파일만 작성합니다

# To-do
- [x] Controller
- [x] Service (Interface 포함)
- [x] Repository (POJO Interface 포함)
- [x] Entity (ETC 참고)

# ETC
단 Entity의 내용은 ERD에 맞춰서 작성되어야 하며 관계가 있는 경우
우선 JPA 연관관계 (`@ManyToOne` 등) 없이 작성합니다. (ex: 페어링이 와인을 소유할 경우, wine: Wine이 아닌 wineId: Long 으로 설정)
