### ISSUE TITLE
✨리뷰 도메인 기본적인 구조만 작성

### ISSUE THREAD

**Issue by mobzzzzz** [spartaKotlinTeamSober/wachu_server#4]
# 기능 설명
리뷰 도메인의 기본적인 구조를 **로직을 제외하고** 기본적인 파일만 작성합니다

# To-do
- [ ] Controller
- [ ] Service (Interface 포함)
- [ ] Repository (POJO Interface 포함)
- [ ] Entity (ETC 참고)

# ETC
단 Entity의 내용은 ERD에 맞춰서 작성되어야 하며 관계가 있는 경우
우선 JPA 연관관계 (@ManyToOne 등) 없이 작성합니다. (ex: 페어링이 와인을 소유할 경우, wine: Wine이 아닌 wineId: Long 으로 설정)

**Comment by mobzzzzz** [comment]
리뷰 도메인에 포함되는 리뷰 멀티미디어 테이블은 아직 S3가 없으므로 추후 포함합니다
