### ISSUE TITLE
✨와인 프로모션/이달의 와인 관련 기능 구현

### ISSUE THREAD

**Issue by mobzzzzz** [spartaKotlinTeamSober/wachu_server#40]
# 기능 설명
프로모션 와인, 이달의 와인을 관리할 수 있는 `wine_promotion` 테이블을 구현하고
프로모션 / 이달의 와인 조회 API를 처리합니다.

추가로 오직 `ADMIN` 유저만이 이용할 수 있는 백오피스 API를 추가합니다.

# To-do
- [x] `wine_promotion` 구조 작성 (Entity등)
- [x] 조회 API
- [x] ADMIN용 백오피스 API (prefix를 /admin/ 등으로 처리할 지 정책적 의사결정이 필요합니다.)
- [x] 테스트 코드 작성

# ETC
해당 기능 일부러 규모를 키운 느낌이 있습니다.
작업자의 판단 하에 유연한 To-do를 결정지으시는 것을 권장드립니다

**Comment by mobzzzzz** [comment]
PR: #54
