### ISSUE TITLE
📝 Readme 작성

### ISSUE THREAD

**Issue by mobzzzzz** [spartaKotlinTeamSober/wachu_server#77]
# 기능 설명
Readme 작성

# To-do
- [x] 목차
- [x] 기술 스택 / 사용 도구 정리 (+ 서비스/시스템 아키텍처?)
- [x] 프로그램 구조 (Use case or 그냥 사용 시나리오, 와이어프레임, ERD, 명세서) + Dataset은 wine21 명시
- [x] 참여 개발자
- [x] 트러블 슈팅 (/articles 폴더 생성해서 5분 기록 보드 문서를 .md 파일로 저장)

# ETC
